import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { useAuth } from "@/lib/auth";
import { getTest, publishTest, startTestAttempt } from "@/lib/tests.functions";

export const Route = createFileRoute("/dashboard/tests/$testId")({
  component: TestDetails,
  head: () => ({ meta: [{ title: "Test details — TSJ Scholar Palanpur" }, { name: "description", content: "Review examination details, instructions and system requirements." }, { property: "og:title", content: "Test details — TSJ Scholar Palanpur" }, { property: "og:description", content: "Professional examination details and instructions." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
});

function TestDetails() {
  const { testId } = Route.useParams(); const { profile } = useAuth();
  const fetchTest = useServerFn(getTest); const publish = useServerFn(publishTest); const start = useServerFn(startTestAttempt);
  const [data,setData]=useState<any>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const load=()=>fetchTest({data:{id:testId}}).then(setData).catch(e=>setError(e.message)); useEffect(()=>{load()},[testId]); // eslint-disable-line
  if(error)return <div role="alert" className="rounded-xl bg-soft-rose p-5 text-destructive">{error}</div>; if(!data)return <div className="h-80 animate-pulse rounded-2xl bg-muted"/>;
  const {test,questions}=data; const staff=profile?.role!=="student";
  const begin=async()=>{setBusy(true);try{const a=await start({data:{testId}}) as any;window.location.href=`/exam/${a.id}`}catch(e){setError(e instanceof Error?e.message:"Could not start test");setBusy(false)}};
  return <div className="mx-auto max-w-5xl space-y-6">
    <Link to="/dashboard/tests" className="text-sm text-primary">← Back to tests</Link>
    <section className="rounded-2xl border border-border bg-card p-6 shadow-soft sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs uppercase tracking-[0.2em] text-gold">{test.exam_type} · Class {test.class_level}</div><h1 className="mt-2 font-display text-4xl">{test.title}</h1><p className="mt-2 text-muted-foreground">Created by {test.profiles?.full_name??"TSJ Faculty"}</p></div><span className="rounded-full bg-soft-primary px-3 py-1 text-xs font-semibold uppercase tracking-widest text-primary">{test.status}</span></div><div className="mt-7 grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Info label="Subjects" value={test.subjects.join(", ")}/><Info label="Questions" value={test.total_questions}/><Info label="Marks" value={test.total_marks}/><Info label="Duration" value={`${test.duration_minutes} min`}/><Info label="Negative" value={`−${test.negative_marks}`}/><Info label="Language" value={test.language}/></div></section>
    <section className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="rounded-2xl border border-border bg-card p-6 shadow-soft"><h2 className="font-display text-2xl">Instructions</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-muted-foreground">{test.instructions||"Read each question carefully. Answers save automatically. Stay in fullscreen."}</p><h3 className="mt-6 font-display text-xl">Paper pattern</h3><div className="mt-3 flex flex-wrap gap-2">{test.question_types.map((x:string)=><span key={x} className="rounded-full border border-border px-3 py-1 text-xs">{x}</span>)}</div>{staff&&<div className="mt-7 border-t border-border pt-5"><h3 className="font-display text-xl">Generated questions</h3><div className="mt-3 space-y-3">{questions.map((q:any,i:number)=><div key={q.id} className="rounded-xl border border-border p-4"><div className="text-[10px] uppercase tracking-widest text-muted-foreground">Q{i+1} · {q.subject} · {q.chapter} · {q.difficulty}</div><div className="mt-2 text-sm leading-relaxed">{q.stem}</div>{(q.diagrams??[]).map((d:any,di:number)=>d?.type==="svg"?<div key={di} className="mt-3 overflow-auto rounded-lg border border-border bg-card p-3" dangerouslySetInnerHTML={{__html:d.content}}/>:null)}</div>)}</div></div>}</div><aside className="space-y-4"><div className="rounded-2xl border border-border bg-card p-5 shadow-soft"><h2 className="font-display text-xl">Exam readiness</h2><ul className="mt-4 space-y-3 text-sm"><Ready text="Same verified paper for everyone"/><Ready text="Question order shuffled per student"/><Ready text="Options shuffled with answer mapping"/><Ready text="Autosave and violation logging"/><Ready text="Version locked after publishing"/></ul>{staff?test.status!=="published"?<button onClick={async()=>{setBusy(true);await publish({data:{id:testId}});await load();setBusy(false)}} disabled={busy||questions.length===0} className="mt-5 w-full rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-40">{busy?"Publishing…":"Publish & lock Version 1"}</button>:<div className="mt-5 rounded-xl bg-soft-emerald p-3 text-center text-sm font-semibold text-emerald">Version 1 is live and locked</div>:<button onClick={begin} disabled={busy||test.status!=="published"} className="mt-5 w-full rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground disabled:opacity-40">{busy?"Preparing secure attempt…":"Continue to system check"}</button>}</div></aside></section>
  </div>;
}
function Info({label,value}:{label:string;value:React.ReactNode}){return <div className="rounded-xl bg-muted p-3"><div className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div><div className="mt-1 text-sm font-semibold">{value}</div></div>}
function Ready({text}:{text:string}){return <li className="flex gap-2"><span className="text-emerald">✓</span><span>{text}</span></li>}