import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/lib/auth";
import { CHAPTERS, EXAM_SUBJECTS, QUESTION_TYPES } from "@/lib/exam-catalog";
import { createTest, listTests } from "@/lib/tests.functions";

export const Route = createFileRoute("/dashboard/tests/")({
  component: TestsPage,
  head: () => ({ meta: [{ title: "Tests — TSJ Scholar Palanpur" }, { name: "description", content: "Create and attempt professional JEE, NEET and school examinations." }, { property: "og:title", content: "Tests — TSJ Scholar Palanpur" }, { property: "og:description", content: "Professional school and competitive examination center." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
});

type TestRow = any;
const initial = { title: "", exam_type: "JEE", class_level: 11, subjects: ["Physics", "Chemistry", "Mathematics"], chapters: {} as Record<string,string[]>, total_questions: 10, total_marks: 40, duration_minutes: 60, positive_marks: 4, negative_marks: 1, partial_marking: false, language: "English", difficulty: { easy: 30, medium: 40, hard: 30 }, question_types: ["MCQ"], instructions: "Read every question carefully. Your answers are autosaved. Remain in fullscreen during the examination.", scheduled_at: "", ends_at: "" };

function TestsPage() {
  const { profile } = useAuth();
  const list = useServerFn(listTests); const create = useServerFn(createTest);
  const [tests, setTests] = useState<TestRow[]>([]); const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false); const [step, setStep] = useState(1); const [form, setForm] = useState(initial); const [error, setError] = useState("");
  const isStaff = profile?.role === "teacher" || profile?.role === "principal";
  const subjects = EXAM_SUBJECTS[form.exam_type as keyof typeof EXAM_SUBJECTS] ?? [];
  const refresh = () => list({}).then((r: any) => setTests(r ?? [])).finally(() => setLoading(false));
  useEffect(() => { refresh(); }, []); // eslint-disable-line

  const toggle = (key: "subjects" | "question_types", value: string) => setForm((f) => ({ ...f, [key]: (f[key] as string[]).includes(value) ? (f[key] as string[]).filter((x) => x !== value) : [...(f[key] as string[]), value] }));
  const toggleChapter = (subject: string, chapter: string) => setForm((f) => { const current = f.chapters[subject] ?? []; return { ...f, chapters: { ...f.chapters, [subject]: current.includes(chapter) ? current.filter((c) => c !== chapter) : [...current, chapter] } }; });
  const valid = useMemo(() => form.title.trim() && form.subjects.length && form.total_questions > 0 && Object.values(form.difficulty).reduce((a,b)=>a+b,0) === 100, [form]);
  const generate = async () => { if (!valid) return; setCreating(true); setError(""); try { const payload = { ...form, scheduled_at: form.scheduled_at ? new Date(form.scheduled_at).toISOString() : null, ends_at: form.ends_at ? new Date(form.ends_at).toISOString() : null }; const result = await create({ data: payload as any }) as { id: string }; window.location.href = `/dashboard/tests/${result.id}`; } catch (e) { setError(e instanceof Error ? e.message : "Could not generate the paper."); setCreating(false); } };

  if (loading) return <div className="space-y-4"><div className="h-12 w-64 animate-pulse rounded bg-muted"/><div className="h-48 animate-pulse rounded-2xl bg-muted"/></div>;
  return <div className="space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs uppercase tracking-[0.2em] text-gold">Examination center</div><h1 className="mt-2 font-display text-4xl text-foreground">{isStaff ? "Tests & papers" : "Upcoming tests"}</h1><p className="mt-2 max-w-2xl text-muted-foreground">{isStaff ? "Build, review, publish and analyse national-level papers." : "Your eligible Class 11 and Class 12 examinations appear here."}</p></div>{isStaff && <button onClick={() => setStep(1)} className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground shadow-soft">+ Create test</button>}</header>
    {isStaff && <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-soft">
      <div className="flex overflow-x-auto border-b border-border bg-muted/40 px-4">{["Exam","Class","Subjects","Chapters","Settings"].map((label,i)=><button key={label} onClick={()=>setStep(i+1)} className={`min-w-28 border-b-2 px-4 py-4 text-xs font-semibold uppercase tracking-widest ${step===i+1?"border-primary text-primary":"border-transparent text-muted-foreground"}`}><span className="mr-2">0{i+1}</span>{label}</button>)}</div>
      <div className="p-5 sm:p-7">
        {step===1 && <div><WizardTitle title="Choose the examination" text="This controls subjects, patterns and difficulty expectations."/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.keys(EXAM_SUBJECTS).map((type)=><Choice key={type} active={form.exam_type===type} onClick={()=>setForm({...form,exam_type:type,subjects:[...EXAM_SUBJECTS[type as keyof typeof EXAM_SUBJECTS]],chapters:{}})} title={type} text={type==="JEE"?"Main & Advanced patterns":type==="NEET"?"NCERT-first medical pattern":type==="School Test"?"Board and classroom papers":"Focused chapter practice"}/>)}</div><Field label="Test name"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="exam-input" placeholder="e.g. JEE Main Physics — Mechanics I"/></Field></div>}
        {step===2 && <div><WizardTitle title="Choose the eligible class" text="Only students assigned to this class can see and attempt the paper."/><div className="grid gap-3 sm:grid-cols-2">{[11,12].map(c=><Choice key={c} active={form.class_level===c} onClick={()=>setForm({...form,class_level:c})} title={`Class ${c}`} text={c===11?"Current student cohort":"Architecture ready for future students"}/>)}</div></div>}
        {step===3 && <div><WizardTitle title="Select subjects" text="Choose one subject, a combination, or the complete stream."/><div className="grid gap-3 sm:grid-cols-3">{subjects.map(s=><Choice key={s} active={form.subjects.includes(s)} onClick={()=>toggle("subjects",s)} title={s} text={`${CHAPTERS[s]?.length ?? 0} chapters available`}/>)}</div></div>}
        {step===4 && <div><WizardTitle title="Select chapters" text="The generator stays inside your selected NCERT syllabus."/><div className="space-y-5">{form.subjects.map(subject=><div key={subject}><div className="mb-2 flex items-center justify-between"><h3 className="font-display text-xl">{subject}</h3><button onClick={()=>setForm(f=>({...f,chapters:{...f.chapters,[subject]:CHAPTERS[subject]??[]}}))} className="text-xs font-semibold text-primary">Select all</button></div><div className="grid gap-2 md:grid-cols-2">{(CHAPTERS[subject]??[]).map((ch,i)=><label key={ch} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm ${form.chapters[subject]?.includes(ch)?"border-primary bg-soft-primary":"border-border"}`}><input type="checkbox" checked={form.chapters[subject]?.includes(ch)??false} onChange={()=>toggleChapter(subject,ch)}/><span className="text-muted-foreground">{i+1}.</span>{ch}</label>)}</div></div>)}</div></div>}
        {step===5 && <div><WizardTitle title="Configure the paper" text="Set marks, time, difficulty, question types and schedule."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="Questions" value={form.total_questions} onChange={v=>setForm({...form,total_questions:v})}/><NumberField label="Total marks" value={form.total_marks} onChange={v=>setForm({...form,total_marks:v})}/><NumberField label="Duration (min)" value={form.duration_minutes} onChange={v=>setForm({...form,duration_minutes:v})}/><NumberField label="Positive marks" value={form.positive_marks} onChange={v=>setForm({...form,positive_marks:v})}/><NumberField label="Negative marks" value={form.negative_marks} onChange={v=>setForm({...form,negative_marks:v})}/><Field label="Language"><select className="exam-input" value={form.language} onChange={e=>setForm({...form,language:e.target.value})}><option>English</option><option>Hindi</option><option>Gujarati</option></select></Field><Field label="Starts"><input type="datetime-local" className="exam-input" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></Field><Field label="Ends"><input type="datetime-local" className="exam-input" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></Field></div><div className="mt-5"><div className="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Difficulty — must total 100%</div><div className="grid gap-3 sm:grid-cols-3">{(["easy","medium","hard"] as const).map(k=><NumberField key={k} label={k} value={form.difficulty[k]} onChange={v=>setForm({...form,difficulty:{...form.difficulty,[k]:v}})}/>)}</div><div className="mt-1 text-xs text-muted-foreground">Current total: {Object.values(form.difficulty).reduce((a,b)=>a+b,0)}%</div></div><div className="mt-5"><div className="mb-2 text-xs uppercase tracking-widest text-muted-foreground">Question types</div><div className="flex flex-wrap gap-2">{QUESTION_TYPES.map(t=><button key={t} onClick={()=>toggle("question_types",t)} className={`rounded-full border px-3 py-2 text-xs ${form.question_types.includes(t)?"border-primary bg-primary text-primary-foreground":"border-border"}`}>{t}</button>)}</div></div><Field label="Instructions"><textarea className="exam-input min-h-24" value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})}/></Field></div>}
        {error&&<div role="alert" className="mt-5 rounded-xl bg-soft-rose p-3 text-sm text-destructive">{error}</div>}
        <div className="mt-7 flex justify-between border-t border-border pt-5"><button disabled={step===1} onClick={()=>setStep(s=>Math.max(1,s-1))} className="rounded-xl border border-border px-4 py-2 text-sm disabled:opacity-30">Previous</button>{step<5?<button onClick={()=>setStep(s=>Math.min(5,s+1))} className="rounded-xl bg-primary px-5 py-2 text-sm font-semibold text-primary-foreground">Continue</button>:<button disabled={!valid||creating} onClick={generate} className="rounded-xl bg-primary px-5 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-40">{creating?"Generating professional paper…":"Generate paper"}</button>}</div>
      </div>
    </section>}
    <section><div className="mb-3 flex items-center justify-between"><h2 className="font-display text-2xl">{isStaff?"Your papers":"Scheduled examinations"}</h2><span className="text-xs text-muted-foreground">{tests.length} tests</span></div>{tests.length===0?<div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center text-muted-foreground">No tests available yet.</div>:<div className="grid gap-4 lg:grid-cols-2">{tests.map(t=><TestCard key={t.id} test={t} student={!isStaff}/>)}</div>}</section>
  </div>;
}

function TestCard({test,student}:{test:any;student:boolean}) { const start=test.scheduled_at?new Date(test.scheduled_at):null; const locked=start?start.getTime()>Date.now():false; const submitted=Boolean(test.my_attempt?.submitted_at); return <article className="rounded-2xl border border-border bg-card p-5 shadow-soft"><div className="flex items-start justify-between gap-3"><div><div className="mb-2 flex flex-wrap gap-2"><Badge>{test.exam_type}</Badge><Badge>{test.stream}</Badge><Badge>Class {test.class_level}</Badge></div><h3 className="font-display text-2xl">{test.title}</h3><p className="mt-1 text-sm text-muted-foreground">{test.subjects.join(" · ")} · by {test.profiles?.full_name??"TSJ Faculty"}</p></div><span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-widest ${submitted||test.status==="published"?"bg-soft-emerald text-emerald":"bg-soft-gold text-gold"}`}>{submitted?"completed":test.status}</span></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric value={`${test.duration_minutes}m`} label="Duration"/><Metric value={submitted?`${Number(test.my_attempt.score??0)}/${Number(test.my_attempt.max_score??0)}`:test.total_questions} label={submitted?"Score":"Questions"}/><Metric value={submitted?`${Number(test.my_attempt.percentage??0).toFixed(1)}%`:test.total_marks} label={submitted?"Result":"Marks"}/></div><div className="mt-4 flex items-center justify-between gap-3"><div className="text-xs text-muted-foreground">{submitted?"Submitted and graded":start?start.toLocaleString():"Available after publishing"}</div>{student&&submitted?<Link to="/exam-results/$attemptId" params={{attemptId:test.my_attempt.id}} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">View result</Link>:<Link to="/dashboard/tests/$testId" params={{testId:test.id}} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{student?(locked?"View details":"Start test"):"Review paper"}</Link>}</div></article> }
function WizardTitle({title,text}:{title:string;text:string}) { return <div className="mb-6"><h2 className="font-display text-3xl">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{text}</p></div> }
function Choice({active,onClick,title,text}:{active:boolean;onClick:()=>void;title:string;text:string}) { return <button onClick={onClick} className={`min-h-28 rounded-xl border p-4 text-left transition ${active?"border-primary bg-soft-primary shadow-soft":"border-border hover:bg-muted"}`}><div className="font-display text-xl">{title}</div><div className="mt-1 text-xs leading-relaxed text-muted-foreground">{text}</div></button> }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="mt-4 block"><span className="mb-1.5 block text-xs uppercase tracking-widest text-muted-foreground">{label}</span>{children}</label> }
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}) { return <Field label={label}><input type="number" min={0} value={value} onChange={e=>onChange(Number(e.target.value))} className="exam-input"/></Field> }
function Badge({children}:{children:React.ReactNode}) { return <span className="rounded-full bg-soft-primary px-2.5 py-1 text-[10px] font-semibold uppercase tracking-widest text-primary">{children}</span> }
function Metric({value,label}:{value:React.ReactNode;label:string}) { return <div className="rounded-xl bg-muted p-3"><div className="font-display text-xl">{value}</div><div className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</div></div> }