/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as LiveControlTokenRouteImport } from './routes/live-control.$token'
import { Route as ExamAttemptIdRouteImport } from './routes/exam.$attemptId'
import { Route as ExamResultsAttemptIdRouteImport } from './routes/exam-results.$attemptId'
import { Route as DashboardTestsRouteImport } from './routes/dashboard.tests'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMaterialsRouteImport } from './routes/dashboard.materials'
import { Route as DashboardGlimpectRouteImport } from './routes/dashboard.glimpect'
import { Route as DashboardGalleryRouteImport } from './routes/dashboard.gallery'
import { Route as DashboardFeesRouteImport } from './routes/dashboard.fees'
import { Route as DashboardDoubtsRouteImport } from './routes/dashboard.doubts'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardAshraRouteImport } from './routes/dashboard.ashra'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard.announcements'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as DashboardTestsIndexRouteImport } from './routes/dashboard.tests.index'
import { Route as DashboardLiveIndexRouteImport } from './routes/dashboard.live.index'
import { Route as DashboardTestsTestIdRouteImport } from './routes/dashboard.tests.$testId'
import { Route as DashboardLiveClassIdRouteImport } from './routes/dashboard.live.$classId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LiveControlTokenRoute = LiveControlTokenRouteImport.update({
  id: '/live-control/$token',
  path: '/live-control/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamAttemptIdRoute = ExamAttemptIdRouteImport.update({
  id: '/exam/$attemptId',
  path: '/exam/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamResultsAttemptIdRoute = ExamResultsAttemptIdRouteImport.update({
  id: '/exam-results/$attemptId',
  path: '/exam-results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestsRoute = DashboardTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaterialsRoute = DashboardMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGlimpectRoute = DashboardGlimpectRouteImport.update({
  id: '/glimpect',
  path: '/glimpect',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGalleryRoute = DashboardGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeesRoute = DashboardFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDoubtsRoute = DashboardDoubtsRouteImport.update({
  id: '/doubts',
  path: '/doubts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAshraRoute = DashboardAshraRouteImport.update({
  id: '/ashra',
  path: '/ashra',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => DashboardRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTestsIndexRoute = DashboardTestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTestsRoute,
} as any)
const DashboardLiveIndexRoute = DashboardLiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestsTestIdRoute = DashboardTestsTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => DashboardTestsRoute,
} as any)
const DashboardLiveClassIdRoute = DashboardLiveClassIdRouteImport.update({
  id: '/live/$classId',
  path: '/live/$classId',
  getParentRoute: () => DashboardRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/ashra': typeof DashboardAshraRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/doubts': typeof DashboardDoubtsRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/glimpect': typeof DashboardGlimpectRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/tests': typeof DashboardTestsRouteWithChildren
  '/exam-results/$attemptId': typeof ExamResultsAttemptIdRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/live-control/$token': typeof LiveControlTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/live/$classId': typeof DashboardLiveClassIdRoute
  '/dashboard/tests/$testId': typeof DashboardTestsTestIdRoute
  '/dashboard/live/': typeof DashboardLiveIndexRoute
  '/dashboard/tests/': typeof DashboardTestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/ashra': typeof DashboardAshraRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/doubts': typeof DashboardDoubtsRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/glimpect': typeof DashboardGlimpectRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/exam-results/$attemptId': typeof ExamResultsAttemptIdRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/live-control/$token': typeof LiveControlTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/live/$classId': typeof DashboardLiveClassIdRoute
  '/dashboard/tests/$testId': typeof DashboardTestsTestIdRoute
  '/dashboard/live': typeof DashboardLiveIndexRoute
  '/dashboard/tests': typeof DashboardTestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/ashra': typeof DashboardAshraRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/doubts': typeof DashboardDoubtsRoute
  '/dashboard/fees': typeof DashboardFeesRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/glimpect': typeof DashboardGlimpectRoute
  '/dashboard/materials': typeof DashboardMaterialsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/tests': typeof DashboardTestsRouteWithChildren
  '/exam-results/$attemptId': typeof ExamResultsAttemptIdRoute
  '/exam/$attemptId': typeof ExamAttemptIdRoute
  '/live-control/$token': typeof LiveControlTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/live/$classId': typeof DashboardLiveClassIdRoute
  '/dashboard/tests/$testId': typeof DashboardTestsTestIdRoute
  '/dashboard/live/': typeof DashboardLiveIndexRoute
  '/dashboard/tests/': typeof DashboardTestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/announcements'
    | '/dashboard/ashra'
    | '/dashboard/calendar'
    | '/dashboard/doubts'
    | '/dashboard/fees'
    | '/dashboard/gallery'
    | '/dashboard/glimpect'
    | '/dashboard/materials'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/students'
    | '/dashboard/tests'
    | '/exam-results/$attemptId'
    | '/exam/$attemptId'
    | '/live-control/$token'
    | '/dashboard/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/live/$classId'
    | '/dashboard/tests/$testId'
    | '/dashboard/live/'
    | '/dashboard/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/announcements'
    | '/dashboard/ashra'
    | '/dashboard/calendar'
    | '/dashboard/doubts'
    | '/dashboard/fees'
    | '/dashboard/gallery'
    | '/dashboard/glimpect'
    | '/dashboard/materials'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/students'
    | '/exam-results/$attemptId'
    | '/exam/$attemptId'
    | '/live-control/$token'
    | '/dashboard'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/live/$classId'
    | '/dashboard/tests/$testId'
    | '/dashboard/live'
    | '/dashboard/tests'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/announcements'
    | '/dashboard/ashra'
    | '/dashboard/calendar'
    | '/dashboard/doubts'
    | '/dashboard/fees'
    | '/dashboard/gallery'
    | '/dashboard/glimpect'
    | '/dashboard/materials'
    | '/dashboard/notifications'
    | '/dashboard/reports'
    | '/dashboard/students'
    | '/dashboard/tests'
    | '/exam-results/$attemptId'
    | '/exam/$attemptId'
    | '/live-control/$token'
    | '/dashboard/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/live/$classId'
    | '/dashboard/tests/$testId'
    | '/dashboard/live/'
    | '/dashboard/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ExamResultsAttemptIdRoute: typeof ExamResultsAttemptIdRoute
  ExamAttemptIdRoute: typeof ExamAttemptIdRoute
  LiveControlTokenRoute: typeof LiveControlTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/live-control/$token': {
      id: '/live-control/$token'
      path: '/live-control/$token'
      fullPath: '/live-control/$token'
      preLoaderRoute: typeof LiveControlTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$attemptId': {
      id: '/exam/$attemptId'
      path: '/exam/$attemptId'
      fullPath: '/exam/$attemptId'
      preLoaderRoute: typeof ExamAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-results/$attemptId': {
      id: '/exam-results/$attemptId'
      path: '/exam-results/$attemptId'
      fullPath: '/exam-results/$attemptId'
      preLoaderRoute: typeof ExamResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tests': {
      id: '/dashboard/tests'
      path: '/tests'
      fullPath: '/dashboard/tests'
      preLoaderRoute: typeof DashboardTestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/materials': {
      id: '/dashboard/materials'
      path: '/materials'
      fullPath: '/dashboard/materials'
      preLoaderRoute: typeof DashboardMaterialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/glimpect': {
      id: '/dashboard/glimpect'
      path: '/glimpect'
      fullPath: '/dashboard/glimpect'
      preLoaderRoute: typeof DashboardGlimpectRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery': {
      id: '/dashboard/gallery'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fees': {
      id: '/dashboard/fees'
      path: '/fees'
      fullPath: '/dashboard/fees'
      preLoaderRoute: typeof DashboardFeesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/doubts': {
      id: '/dashboard/doubts'
      path: '/doubts'
      fullPath: '/dashboard/doubts'
      preLoaderRoute: typeof DashboardDoubtsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ashra': {
      id: '/dashboard/ashra'
      path: '/ashra'
      fullPath: '/dashboard/ashra'
      preLoaderRoute: typeof DashboardAshraRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tests/': {
      id: '/dashboard/tests/'
      path: '/'
      fullPath: '/dashboard/tests/'
      preLoaderRoute: typeof DashboardTestsIndexRouteImport
      parentRoute: typeof DashboardTestsRoute
    }
    '/dashboard/live/': {
      id: '/dashboard/live/'
      path: '/live'
      fullPath: '/dashboard/live/'
      preLoaderRoute: typeof DashboardLiveIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tests/$testId': {
      id: '/dashboard/tests/$testId'
      path: '/$testId'
      fullPath: '/dashboard/tests/$testId'
      preLoaderRoute: typeof DashboardTestsTestIdRouteImport
      parentRoute: typeof DashboardTestsRoute
    }
    '/dashboard/live/$classId': {
      id: '/dashboard/live/$classId'
      path: '/live/$classId'
      fullPath: '/dashboard/live/$classId'
      preLoaderRoute: typeof DashboardLiveClassIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardTestsRouteChildren {
  DashboardTestsTestIdRoute: typeof DashboardTestsTestIdRoute
  DashboardTestsIndexRoute: typeof DashboardTestsIndexRoute
}

const DashboardTestsRouteChildren: DashboardTestsRouteChildren = {
  DashboardTestsTestIdRoute: DashboardTestsTestIdRoute,
  DashboardTestsIndexRoute: DashboardTestsIndexRoute,
}

const DashboardTestsRouteWithChildren = DashboardTestsRoute._addFileChildren(
  DashboardTestsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardAshraRoute: typeof DashboardAshraRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardDoubtsRoute: typeof DashboardDoubtsRoute
  DashboardFeesRoute: typeof DashboardFeesRoute
  DashboardGalleryRoute: typeof DashboardGalleryRoute
  DashboardGlimpectRoute: typeof DashboardGlimpectRoute
  DashboardMaterialsRoute: typeof DashboardMaterialsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardTestsRoute: typeof DashboardTestsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardLiveClassIdRoute: typeof DashboardLiveClassIdRoute
  DashboardLiveIndexRoute: typeof DashboardLiveIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardAshraRoute: DashboardAshraRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardDoubtsRoute: DashboardDoubtsRoute,
  DashboardFeesRoute: DashboardFeesRoute,
  DashboardGalleryRoute: DashboardGalleryRoute,
  DashboardGlimpectRoute: DashboardGlimpectRoute,
  DashboardMaterialsRoute: DashboardMaterialsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardTestsRoute: DashboardTestsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardLiveClassIdRoute: DashboardLiveClassIdRoute,
  DashboardLiveIndexRoute: DashboardLiveIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ExamResultsAttemptIdRoute: ExamResultsAttemptIdRoute,
  ExamAttemptIdRoute: ExamAttemptIdRoute,
  LiveControlTokenRoute: LiveControlTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
